CREATE TABLE respuesta (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
mensaje TEXT NOT NULL,
topico BIGINT NOT NULL,
fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
autor BIGINT NOT NULL,
solucion BOOLEAN DEFAULT FALSE,
FOREIGN KEY (topico) REFERENCES topico(id) ON DELETE CASCADE,
FOREIGN KEY (autor) REFERENCES usuario(id) ON DELETE CASCADE
);